#!/usr/bin/env bash
set -euo pipefail

# Controller-lite worker for the M01 RDMA lab.
#
# It processes queued request files generated by testops-ci-submit.sh, takes a
# single lab lock, runs scripts/run-rdma-ci.sh, and moves each request to done or
# failed. This is deliberately boring: systemd can run it as a service, cron can
# run it periodically, and the dashboard remains read-only over result bundles.

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

QUEUE_DIR="${TESTOPS_QUEUE_DIR:-/mnt/smb/work/share/testops/queue/rdma-ci}"
STATE_DIR="${TESTOPS_STATE_DIR:-/mnt/smb/work/share/testops/state/rdma-ci}"
LOCK_FILE="${TESTOPS_LOCK_FILE:-/mnt/smb/work/share/testops/locks/rdma-lab.lock}"
LOG_DIR="${TESTOPS_LOG_DIR:-/mnt/smb/work/share/testops/logs/rdma-ci}"
POLL_SECONDS="${TESTOPS_POLL_SECONDS:-10}"
ONCE="${TESTOPS_ONCE:-false}"
RUN_SCRIPT="${TESTOPS_RDMA_CI_SCRIPT:-./scripts/run-rdma-ci.sh}"

mkdir -p "$QUEUE_DIR" "$STATE_DIR"/{running,done,failed} "$(dirname "$LOCK_FILE")" "$LOG_DIR"

have_flock=false
if command -v flock >/dev/null 2>&1; then
  have_flock=true
fi

run_request() {
  local req="$1"
  local base
  base="$(basename "$req" .env)"
  local running="${STATE_DIR}/running/${base}.env"
  local done="${STATE_DIR}/done/${base}.env"
  local failed="${STATE_DIR}/failed/${base}.env"
  local log="${LOG_DIR}/${base}.log"

  if ! mv "$req" "$running" 2>/dev/null; then
    return 0
  fi

  echo "[$(date -Is)] starting $base" | tee -a "$log"
  set +u
  # shellcheck disable=SC1090
  source "$running"
  set -u

  local status=0
  (
    export TESTOPS_MONO_REF TESTOPS_MONO_REPO TESTOPS_RUN_BY TESTOPS_TEAM TESTOPS_PROJECT TESTOPS_TEST_ID TESTOPS_BRANCH TESTOPS_COMMIT
    "$RUN_SCRIPT"
  ) >>"$log" 2>&1 || status=$?

  if [[ "$status" -eq 0 ]]; then
    mv "$running" "$done"
    echo "[$(date -Is)] pass $base" | tee -a "$log"
  else
    mv "$running" "$failed"
    echo "[$(date -Is)] fail $base status=$status" | tee -a "$log"
  fi
  return "$status"
}

process_once() {
  local req
  req="$(find "$QUEUE_DIR" -maxdepth 1 -type f -name '*.env' | sort | head -n 1)"
  if [[ -z "$req" ]]; then
    return 0
  fi

  if [[ "$have_flock" == true ]]; then
    (
      flock 9
      run_request "$req"
    ) 9>"$LOCK_FILE"
  else
    mkdir "${LOCK_FILE}.dir" 2>/dev/null || {
      echo "lab lock busy: ${LOCK_FILE}.dir"
      return 0
    }
    trap 'rmdir "${LOCK_FILE}.dir" 2>/dev/null || true' RETURN
    run_request "$req"
  fi
}

if [[ "${1:-}" == "--once" ]]; then
  ONCE=true
fi

while true; do
  process_once || true
  if [[ "$ONCE" == true ]]; then
    break
  fi
  sleep "$POLL_SECONDS"
done
